### ISSUE TITLE
You do not restore cursor at the end

### ISSUE THREAD

**Issue by gcarreno** [silvericedan/Thorny_Forest#1]
Hi Reinaldo(@silvericedan),

Could you please restore the cursor at the end of the game?
You call:
```pascal
procedure Initial(); {INICIA RANDOMIZE Y DA LA PANTALLA DE PRESENTACION}
        BegiN
                cursoroff; {apaga el cursor para que no titilee}
```

But then when ending you don't turn the cursor on:
```pascal
        writeln('                                  ENDING THE GAME...');
        writeln('                               PRESS ANY KEY TO EXIT');
        readkey;
END.
```

Many thanks!!

Cheers,
Gus

PS: Have you had a look at what Chris(@cyberfilth) is doing with his [Axes Armour & Ale](https://github.com/cyberfilth/Axes-Armour-Ale)?

**Comment by silvericedan** [comment]
Yes, i can work on it this weekend and fix this. 
Wow Axes Armour & Ale looks amazing!!

**Comment by gcarreno** [comment]
Hi Reinaldo(@silvericedan),

> Yes, i can work on it this weekend and fix this.

Many, many thanks!!

> Wow Axes Armour & Ale looks amazing!!

It does, doesn't it?!?! :+1: 

Cheers,
Gus

**Comment by silvericedan** [comment]
fixed on 5d8d5c450d ! i couldnt wait to weekend, installed back lazarus pascal and here we are!

Cheers!
Reinaldo

**Comment by gcarreno** [comment]
Hi Reinaldo(@silvericedan),

> i couldnt wait to weekend, installed back lazarus pascal and here we are!

Ehehehe, I completely understand!! One gets giddy when other take interest in our work :wink: 

On a different note, could you please do me a favour and do this:
```console
$ git rm --cached ThornyForest.exe
```

And do the same with the `backup` and `lib` folders?

All VCS(Version Control Systems) are optimized for text, not binaries, so having binaries laying around isn't the best.
And, of course, Lazarus/FPC is multiplatform. I'm on an Ubuntu Linux 20.10 64b and you're on Win64, but I'm still testing your stuff both on a Linux format and Windows via wine.
So leaving the least platform specific files is usually considered good practices. :smile: 

After that, please consider adding one or both of `.gitignore` / `.gitattributes`.

You could look at some, slightly fine tuned for Delphi/Lazarus/FPC, under my project: [laz-JSON-Viewer](https://github.com/gcarreno/laz-JSON-Viewer). I think those are my most recent versions of both.
Use them at will, just take care to edit the first lines of `.gitignore` and the last lines of `.gitattributes` to reflect your needs/context.
Remember that if your executable is named `ThornyForest.exe` under windows, it will compile to `ThornyForest` under Linux.

What I do, to avoid having to git ignore those, is that I drop all my binaries under a folder called bin, and THEN ignore that:
```gitignore
# Ignore the top level bin folder
/bin
```

Under Lazarus, Project Options, Paths:
![lazarus-project-options-paths](https://user-images.githubusercontent.com/81799/108915298-95db2780-7624-11eb-8c59-5cc739d51ba4.png)


Many thanks for the quick turn-around!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hi Reinaldo(@silvericedan),

I completely forgot to mention that you should also remove `*.lps` from the repo.
That's your Lazarus Project Session and may contain private and sensible info in it.

Sorry, was having a second look and notices you had it on the repo.

Cheers,
Gus

**Comment by silvericedan** [comment]
Hi Gus!
Thank you very much for taking the time for gifting me this amount of guide and information!!!
I was trying to set up a bin folder but i didnt find how to do it in the proyect settings. 
Also, how should i share a compiled version to some friends that dont are programmers? Its there some good practice way of doing it? It seems github have something called github pages but i dont know if it has hosting for files. That may be a good way?

Cheers,
Reinaldo

**Comment by gcarreno** [comment]
Hi Reinaldo(@silvericedan),

> Thank you very much for taking the time for gifting me this amount of guide and information!!!

No probs my friend, you're quite welcome!!

When you want to distribute binaries you usually do a release and upload your compiled binaries.
That way, you don't overwrite the same executable and you have historic versions of it.

Here's a simple step by step process(Please investigate further each step for better grasp):
1. You tag your current progress:
```console
$ git tag -a v1.0 -m "Release v1.0"
```
2. You push to `origin`:
```console
$ git push --tags
```
3. You now have a tag under your Releases page of this project
4. Click on the "Draft a release" button that now appears
5. Fill in the tag: `v1.0`
6. Fill in the Title and Description
7. Click below the Description to upload some binaries/ Drop them from File Explorer
8. Click on the Green button to Publish/Release

If you need a bit more info, I can add some screen shots, but I don't have a planed release in any of my projects, so it can take some time.

If you look at my project [laz-JSON-Viewer Releases](https://github.com/gcarreno/laz-JSON-Viewer/releases) I have 7 assets:
- The first is just a compressed package of the executable and translation files for Linux(32b)
- The second is just a compressed package of the executable and translation files for Linux(64b)
- The third is just a compressed package of the executable and translation files for Windows(32b)
- The fourth is an InnoSetup executable that install a Windows version according to the user's system.
- The fifth is just a compressed package of the executable and translation files for Windows(64b)
- The last 2 ones are just the compressed sources that you get when you call `git archive`
  These are always present in any release and you have no comtrol over them.

Hope this helps!!

Cheers,
Gus

PS: I hope you're installing your Lazarus with [fpcupdeluxe](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases). It's the best thing **EVAH** to install multiple versions of Lazarus in parallel. Or just one instance, but with cross compilation into many platforms. It's what I use in my system to do Linux 32/64b, Windows 32/64b. I want to do ARM also, but haven't installed the cross compilation stuff and I'm doing it on my Raspberry Pi 3 :smile:

**Comment by silvericedan** [comment]
https://github.com/silvericedan/Thorny_Forest/issues/1#issuecomment-784553374
Updated the gitignore and removed all compiled files!!

**Comment by gcarreno** [comment]
Hi Reinaldo(@silvericedan),

Thanks!!
But you removed too much as I state in #2 :smile: 

Cheers,
Gus

**Comment by gcarreno** [comment]
Closing by 5d8d5c4 I guess
