### ISSUE TITLE
The project needs the *.lpi file you deleted

### ISSUE THREAD

**Issue by gcarreno** [silvericedan/Thorny_Forest#2]
Hey Reinaldo(@silvericedan),

I'm glad that you got rid of most of the binaries and files with personal data, but the `*.lpi` is not one of those.
That's the project info and you'll need to provide that unless you want people complaining that Lazarus is always asking to recreating it.

Cheers,
Gus

**Comment by silvericedan** [comment]
Restored on 8826ae39eac28d603f23769c15c5f51e5c25ef58! Happy New Year Gus @gcarreno !
